version: '3'

services:
  v2ray:
    image: v2fly/v2fly-core  # 指定使用的镜像
    container_name: v2ray  # 指定容器名称
    restart: unless-stopped  # 指定容器重启策略 (除非停止，否则不重启)
    ports:
      - "8000:8000"  # 映射容器端口 10086 到主机端口 10086
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json  # 挂载本地配置文件到容器的 /etc/v2ray/config.json

    # 这段是可选的，用于指定 v2ray 的运行命令
    command: # 可选，指定容器启动命令
      - /usr/bin/v2ray
      - -c
      - /etc/v2ray/config.jso
    networks:
      - flyserver

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    restart: always
    networks:
      - flyserver

networks:
  flyserver:
    driver: bridge
