version: '3'

services:
  v2ray:
    container_name: v2ray_cdn
    image: v2ray/official
    command: run -c /etc/v2ray/config.json
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json
    ports:
      - "8888:8888"
    restart: always
    networks:
      - flyserver

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    restart: always
    networks:
      - flyserver

networks:
  flyserver:
    driver: bridge
