version: '3'

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
      - VIRTUAL_HOST=YOUR_DOMAIN
      - LETSENCRYPT_HOST=YOUR_DOMAIN
      - VIRTUAL_PORT=1310
    volumes:
      - './v2ray/config:/etc/v2ray/'
    networks:
      - flyserver

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    restart: always
    networks:
      - flyserver

networks:
  flyserver:
    driver: bridge
